### ISSUE TITLE
High CPU usage with cgo based project

### ISSUE THREAD

**Issue by triztian** [sourcegraph/go-langserver#338] opened 2018-11-07 23:41 UTC
I'm experiencing High CPU usage only with a project that uses cgo:

```
GOARCH="amd64"
GOBIN="/Users/tristian/go/bin"
GOCACHE="/Users/tristian/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tristian/go"
GORACE=""
GOROOT="/usr/local/Cellar/go@1.10/1.10.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.10/1.10.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g1/v3hz1sm92nv7wbzpg3dx_h_h0000gp/T/go-build244207331=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

VSCode Version:
```
Version 1.28.2 (1.28.2)
```

Go Extension Version:
```
0.7.0 - 6th November, 2018
```

go-langserver version:

```
go-langserver --version
v3-dev
```

```
Showing top 10 nodes out of 35
      flat  flat%   sum%        cum   cum%
     9.91s 72.65% 72.65%     13.10s 96.04%  runtime.scanobject
     1.39s 10.19% 82.84%      1.39s 10.19%  runtime.heapBits.bits (inline)
     1.32s  9.68% 92.52%      1.32s  9.68%  runtime.(*mspan).base (inline)
     0.22s  1.61% 94.13%      0.22s  1.61%  runtime.kevent
     0.19s  1.39% 95.53%      0.19s  1.39%  runtime.markBits.isMarked (inline)
     0.16s  1.17% 96.70%      1.49s 10.92%  runtime.heapBitsForObject
     0.11s  0.81% 97.51%      0.11s  0.81%  runtime.duffcopy
     0.09s  0.66% 98.17%      0.29s  2.13%  runtime.greyobject
     0.09s  0.66% 98.83%      0.09s  0.66%  syscall.Syscall
     0.03s  0.22% 99.05%      0.24s  1.76%  runtime.netpoll
```
```
ID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS         %CPU_ME %CPU_OTHRS UID  FAULTS    COW     MSGSENT    MSGRECV    SYSBSD    SYSMACH
47838  go-langserve 113.6 31:48.92 25     0    91    890M+  0B     33G-   1540  39379 stuck    *0[1]          0.00000 0.00000    502  51354183+ 637400  130        44         30701229+ 384024+
311    iTerm2       39.8  40:52.78 15     9    379+  88M+   72K-   87M-   311   1     sleeping *0[1105]       0.10889 0.77489    502  3557239+  15294+  3266461+   435294+    6365659+  6989728+
0      kernel_task  38.1  02:31:45 140/8  0    2     9797M- 0B     0B     0     0     running   0[0]          0.00000 0.00000    0    135514    0       101816739+ 85572233+  0         0
10310  iTunes       31.7  03:07:27 24/1   4    551   2780K  0B     46M    10310 1     running  *0[284]        0.00000 0.00000    502  177719    1649    594750809+ 198272062+ 185
```

**Comment by keegancsmith** [comment] 2018-11-08 07:39
I don't think this is due to cgo, we have issues around high cpu usage in general.

Duplicate of https://github.com/sourcegraph/go-langserver/issues/209

**Closed by keegancsmith** 2018-11-08 07:39 UTC

**Comment by triztian** [comment] 2018-11-08 16:39
Thanks!, it only happens when I work on a project that uses a cgo lib and when the code has errors (as a type the code and it's incomplete); it will start having really high cpu usage.
