### ISSUE TITLE
ERROR: Initialize rootPath URI is deprecated. Use rootUri instead

### ISSUE THREAD

**Issue by yujiahaol68** [sourcegraph/go-langserver#274] opened 2018-05-08 04:17 UTC
go version: go1.10.2 darwin/amd64

After I upgrade go and vscode-go tools, every time I edit project files it log:

```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///Users/user/go/src/github.com/yujiahaol68/myGoProject") is deprecated. Use rootUri instead.

[Error - 11:57:56] Request textDocument/hover failed.
  Message: no declaration found for checkpoint
  Code: 0
```

**Comment by keegancsmith** [comment] 2018-05-08 09:50
Duplicate of https://github.com/Microsoft/vscode-go/issues/1662

**Closed by keegancsmith** 2018-05-08 09:50 UTC

**Comment by oblitum** [comment] 2018-12-19 20:11
I get this on (Neo)Vim with coc.nvim, I install language server with `go get -u github.com/sourcegraph/go-langserver` and configure it to be used from (Neo)Vim, how is it a duplicate of vscode issue?

I've hit here to check where the protocol changed from `rootPath URI` to `rootUri` to report coc.nvim's author of such change, but got confused instead.

**Comment by oblitum** [comment] 2018-12-19 20:14
I will try [bingo](https://github.com/sourcegraph/go-langserver/issues/350#issuecomment-447230063).
