### ISSUE TITLE
Support symbol renaming

### ISSUE THREAD

**Issue by dsvensson** [sourcegraph/go-langserver#220] opened 2017-12-22 08:45 UTC
Currently [go-rename](https://godoc.org/golang.org/x/tools/cmd/gorename) exists ([MELPA](https://melpa.org/#/go-rename)), but is excruciatingly slow on even small code-bases. It would be really nice to have [rename-support](https://microsoft.github.io/language-server-protocol/specification#rename-request-leftwards_arrow_with_hook) via go-langserver.

**Comment by keegancsmith** [comment] 2017-12-22 09:19
This has been debated a few times in go tools issues. The problem is go guru/rename/mvpkg/etc have a concept of scope which very often defaults to your whole `GOPATH`. So go rename is slow because it is inspecting your whole GOPATH.

However, earlier this year there was mention of the go team improving this https://github.com/golang/go/issues/10917#issuecomment-284481820

But I think it is worth implementing this ourselves in go-langserver since we have the additional concept of a workspace so we can limit the rename work to just the current workspace. We do the same for find references, which is why find references is likely faster in go-langserver than the usual vscode-go shelling out to guru.

I'll happily accept patches around this since I won't have time to work on this soon.

**Comment by dsvensson** [comment] 2017-12-22 09:38
At least in my environment, all application git-repos are GOPATH roots, so I clone example project foo.git to directory foo, and will then have foo/.git, foo/src/foo/main.go, foo/src/vendor/bar etc. go-projectile detects this and configures GOPATH accordingly and lets guru and all other tools play nice in emacs. I haven't used go-langserver yet, found it just an hour ago and I'm excited to try it out. How does it deal with GOPATH, from what I can tell, emacs doesn't send GOPATH to it at least. Should probably just play around with it instead of asking silly questions here :)

**Comment by keegancsmith** [comment] 2017-12-22 10:21
aah, and its still slow? Then I'm not sure if we could make it faster. Although in theory it should be as fast as find references which we have made faster than go guru.

**Comment by Dbz** [comment] 2018-11-25 00:59
I am just commenting to say I would also love to have go-langserver support symbol renaming 👍 !

**Comment by harrisonthorne** [comment] 2018-11-26 16:50
Can this issue be marked as closed as of #337 ?

**Closed** 2018-11-26 17:04 UTC
Labels: enhancement
