### ISSUE TITLE
There may be a memory leak? 

### ISSUE THREAD

**Issue by KISSMonX** [sourcegraph/go-langserver#208] opened 2017-10-20 01:49 UTC
![cc859af8-2b72-4be2-8bee-7510fdbe2e1d](https://user-images.githubusercontent.com/2876745/31801593-e64ca49e-b50e-11e7-9cdc-04b8aa395c91.png)

**Comment by keegancsmith** [comment] 2017-10-20 08:52
@KISSMonX Could you update your go langserver? This is likely a duplicate of the now fixed issue https://github.com/sourcegraph/go-langserver/issues/178

**Comment by leaxoy** [comment] 2017-10-20 10:08
same issue

**Comment by leaxoy** [comment] 2017-10-20 10:16
This extension looks unavailable, there is my config: `-usebinarypkgcache=false -trace`, after a while, memory usage increase crazy, then will be killed by system.

**Comment by leaxoy** [comment] 2017-10-20 10:17
Is there any way for user to debug this extension, may be I can provide more log with debug info

**Comment by slimsag** [comment] 2017-10-20 10:21
Please try without setting usebinarypkgcache=false, that will cause greatly
instead memory usage.

If still having a problem, see readme to capture a heap profile please.

On Oct 20, 2017 3:17 AM, "lixiaohui" <notifications@github.com> wrote:

Is there any way for user to debug this extension, may be I can provide
more log with debug info

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sourcegraph/go-langserver/issues/208#issuecomment-338167086>,
or mute the thread

**Comment by leaxoy** [comment] 2017-10-20 10:26
Ohh, but without this option for some package the hover info is missing.

**Comment by leaxoy** [comment] 2017-10-20 10:49
Looks as if during my type sending `contentChanges` event, memory increase crazy.

**Comment by keegancsmith** [comment] 2017-10-20 12:20
We don't support using that option in a desktop environment. It is used in our server environment where the working copy is immutable and type information is shared between different working copies.

If you do not have memory issues without the flag, are you happy to close this and file an issue for the missing hover info?

**Comment by leaxoy** [comment] 2017-10-20 12:25
Sure, thank you! However, this issue isn't open by me 🤪

**Closed** 2018-02-13 12:23 UTC
