### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by elgatito** [sourcegraph/go-langserver#275] opened 2018-05-08 04:58 UTC
Hello. 

I was using go-langserver for a long time with Atom IDE. It was working fine. 
Then one time I've upgraded to Go 1.10 (and now 1.10.1) and latest Atom/go-langserver and started to get system overloads, caused by go-langserver.

go-langserver: latest
OS: Ubuntu 16.04
Go:
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/elgatito/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/elgatito/go"
GORACE=""
GOROOT="/snap/go/1880"
GOTMPDIR=""
GOTOOLDIR="/snap/go/1880/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build879049061=/tmp/go-build -gno-record-gcc-switches"
```
Example when issue is starting:
`15254 elgatito  20   0 2734880 2,145g   3868 S 151,9 37,5   3:07.01 /home/elgatito/go/bin/go-langserver -gocodecompletion `

Usually it looks like this (when working fine):
`19406 elgatito  20   0  204964  11712   9348 S   1,0  0,2   0:01.33 /home/elgatito/go/bin/go-langserver -gocodecompletion`

It can happen any time, sometimes every few minutes, sometimes not seeing for an hour. 
I have tried to run profile, but I don't see go-langserver listening the port.

**Comment by elgatito** [comment] 2018-05-08 06:09
Github misses OnHold state. 

I've just updated to Go 1.10.2 and rebuilding all the packages I have in $GOPATH. 
I have seen go-langserver from that time in process list, consuming CPU, but not 100% and without memory usage, will keep testing.

**Comment by elgatito** [comment] 2018-05-08 06:46
My happiness was too early. 
Now again getting CPU issues.
I have completed `$ go get -u -x ./..` in my project directory, to recompile for newer Go, and after that - i'm getting CPU issues.

How can I help to investigate it?

**Comment by keegancsmith** [comment] 2018-05-08 09:52
If I am not mistaken this will be solved by https://github.com/sourcegraph/go-langserver/issues/268 So will mark as duplicate

Duplicate of https://github.com/sourcegraph/go-langserver/issues/268

**Closed by keegancsmith** 2018-05-08 09:52 UTC

**Comment by elgatito** [comment] 2018-05-29 07:36
Have moved to a new device, new Ubuntu 18.04, clean system, clean Golang installation (still snap's one), 1.10.2. Same project and having CPU hangs again... 
Maybe it's related to my project of something?
